// LEAGUES
export const LEAGUES = [
  // --- BANKER LEAGUES (9) ---
  { id: 'pl', name: 'Premier League', country: 'England', type: 'banker' },
  { id: 'ch', name: 'Championship', country: 'England', type: 'banker' },
  { id: 'l1', name: 'League 1', country: 'England', type: 'banker' },
  { id: 'l2', name: 'League 2', country: 'England', type: 'banker' },
  { id: 'spl', name: 'Scottish Premiership', country: 'Scotland', type: 'banker' },
  { id: 'laliga', name: 'La Liga', country: 'Spain', type: 'banker' },
  { id: 'bundesliga', name: 'Bundesliga', country: 'Germany', type: 'banker' },
  { id: 'seriea', name: 'Serie A', country: 'Italy', type: 'banker' },
  { id: 'ligue1', name: 'Ligue 1', country: 'France', type: 'banker' },

  // --- COVER LEAGUES (13) ---
  { id: 'superlig', name: 'Süper Lig', country: 'Turkey', type: 'cover' },
  { id: 'portugal', name: 'Liga Portugal', country: 'Portugal', type: 'cover' },
  { id: 'jupiler', name: 'Jupiler Pro League', country: 'Belgium', type: 'cover' },
  { id: 'eredivisie', name: 'Eredivisie', country: 'Netherlands', type: 'cover' },
  { id: 'greek', name: 'Super League Greece', country: 'Greece', type: 'cover' },
  { id: 'swiss', name: 'Swiss Super League', country: 'Switzerland', type: 'cover' },
  { id: 'austrian', name: 'Austrian Bundesliga', country: 'Austria', type: 'cover' },
  { id: 'danish', name: 'Danish Superliga', country: 'Denmark', type: 'cover' },
  { id: 'norwegian', name: 'Eliteserien', country: 'Norway', type: 'cover' },
  { id: 'swedish', name: 'Allsvenskan', country: 'Sweden', type: 'cover' },
  { id: 'czech', name: 'Czech First League', country: 'Czech Republic', type: 'cover' },
  { id: 'croatian', name: 'HNL', country: 'Croatia', type: 'cover' },
  { id: 'polish', name: 'Ekstraklasa', country: 'Poland', type: 'cover' },
];

// TEAMS (Approx 350+ teams)
export const TEAMS = [
  // ==========================
  // BANKER LEAGUES
  // ==========================

  // --- Premier League (20) ---
  { id: 'pl-ars', name: 'Arsenal', country: 'England', league_id: 'pl' },
  { id: 'pl-av', name: 'Aston Villa', country: 'England', league_id: 'pl' },
  { id: 'pl-bou', name: 'Bournemouth', country: 'England', league_id: 'pl' },
  { id: 'pl-bre', name: 'Brentford', country: 'England', league_id: 'pl' },
  { id: 'pl-bha', name: 'Brighton', country: 'England', league_id: 'pl' },
  { id: 'pl-bur', name: 'Burnley', country: 'England', league_id: 'pl' },
  { id: 'pl-che', name: 'Chelsea', country: 'England', league_id: 'pl' },
  { id: 'pl-pal', name: 'Crystal Palace', country: 'England', league_id: 'pl' },
  { id: 'pl-eve', name: 'Everton', country: 'England', league_id: 'pl' },
  { id: 'pl-ful', name: 'Fulham', country: 'England', league_id: 'pl' },
  { id: 'pl-lee', name: 'Leeds United', country: 'England', league_id: 'pl' },
  { id: 'pl-liv', name: 'Liverpool', country: 'England', league_id: 'pl' },
  { id: 'pl-mci', name: 'Man City', country: 'England', league_id: 'pl' },
  { id: 'pl-mun', name: 'Man Utd', country: 'England', league_id: 'pl' },
  { id: 'pl-new', name: 'Newcastle', country: 'England', league_id: 'pl' },
  { id: 'pl-nfo', name: 'Nottm Forest', country: 'England', league_id: 'pl' },
  { id: 'pl-sun', name: 'Sunderland', country: 'England', league_id: 'pl' },
  { id: 'pl-tot', name: 'Tottenham', country: 'England', league_id: 'pl' },
  { id: 'pl-whu', name: 'West Ham', country: 'England', league_id: 'pl' },
  { id: 'pl-wol', name: 'Wolves', country: 'England', league_id: 'pl' },

  // --- Championship (24) ---
  { id: 'ch-bir', name: 'Birmingham City', country: 'England', league_id: 'ch' },
  { id: 'ch-bla', name: 'Blackburn', country: 'England', league_id: 'ch' },
  { id: 'ch-bri', name: 'Bristol City', country: 'England', league_id: 'ch' },
  { id: 'ch-cha', name: 'Charlton', country: 'England', league_id: 'ch' },
  { id: 'ch-cov', name: 'Coventry', country: 'England', league_id: 'ch' },
  { id: 'ch-der', name: 'Derby County', country: 'England', league_id: 'ch' },
  { id: 'ch-hul', name: 'Hull City', country: 'England', league_id: 'ch' },
  { id: 'ch-ips', name: 'Ipswich Town', country: 'England', league_id: 'ch' },
  { id: 'ch-lei', name: 'Leicester City', country: 'England', league_id: 'ch' },
  { id: 'ch-mid', name: 'Middlesbrough', country: 'England', league_id: 'ch' },
  { id: 'ch-mil', name: 'Millwall', country: 'England', league_id: 'ch' },
  { id: 'ch-nor', name: 'Norwich City', country: 'England', league_id: 'ch' },
  { id: 'ch-oxf', name: 'Oxford United', country: 'England', league_id: 'ch' },
  { id: 'ch-por', name: 'Portsmouth', country: 'England', league_id: 'ch' },
  { id: 'ch-pre', name: 'Preston', country: 'England', league_id: 'ch' },
  { id: 'ch-qpr', name: 'QPR', country: 'England', league_id: 'ch' },
  { id: 'ch-she', name: 'Sheffield Utd', country: 'England', league_id: 'ch' },
  { id: 'ch-shw', name: 'Sheffield Wed', country: 'England', league_id: 'ch' },
  { id: 'ch-sou', name: 'Southampton', country: 'England', league_id: 'ch' },
  { id: 'ch-sto', name: 'Stoke City', country: 'England', league_id: 'ch' },
  { id: 'ch-swa', name: 'Swansea', country: 'England', league_id: 'ch' },
  { id: 'ch-wat', name: 'Watford', country: 'England', league_id: 'ch' },
  { id: 'ch-wba', name: 'West Brom', country: 'England', league_id: 'ch' },
  { id: 'ch-wre', name: 'Wrexham', country: 'England', league_id: 'ch' },

  // --- League 1 (24) ---
  { id: 'l1-afc', name: 'AFC Wimbledon', country: 'England', league_id: 'l1' },
  { id: 'l1-bar', name: 'Barnsley', country: 'England', league_id: 'l1' },
  { id: 'l1-bla', name: 'Blackpool', country: 'England', league_id: 'l1' },
  { id: 'l1-bol', name: 'Bolton', country: 'England', league_id: 'l1' },
  { id: 'l1-bra', name: 'Bradford City', country: 'England', league_id: 'l1' },
  { id: 'l1-bur', name: 'Burton Albion', country: 'England', league_id: 'l1' },
  { id: 'l1-car', name: 'Cardiff', country: 'Wales', league_id: 'l1' },
  { id: 'l1-don', name: 'Doncaster Rovers', country: 'England', league_id: 'l1' },
  { id: 'l1-exe', name: 'Exeter City', country: 'England', league_id: 'l1' },
  { id: 'l1-hud', name: 'Huddersfield', country: 'England', league_id: 'l1' },
  { id: 'l1-ley', name: 'Leyton Orient', country: 'England', league_id: 'l1' },
  { id: 'l1-lin', name: 'Lincoln City', country: 'England', league_id: 'l1' },
  { id: 'l1-lut', name: 'Luton Town', country: 'England', league_id: 'l1' },
  { id: 'l1-man', name: 'Mansfield Town', country: 'England', league_id: 'l1' },
  { id: 'l1-nor', name: 'Northampton', country: 'England', league_id: 'l1' },
  { id: 'l1-pet', name: 'Peterborough', country: 'England', league_id: 'l1' },
  { id: 'l1-ply', name: 'Plymouth', country: 'England', league_id: 'l1' },
  { id: 'l1-por', name: 'Port Vale', country: 'England', league_id: 'l1' },
  { id: 'l1-rea', name: 'Reading', country: 'England', league_id: 'l1' },
  { id: 'l1-rot', name: 'Rotherham', country: 'England', league_id: 'l1' },
  { id: 'l1-ste', name: 'Stevenage', country: 'England', league_id: 'l1' },
  { id: 'l1-sto', name: 'Stockport', country: 'England', league_id: 'l1' },
  { id: 'l1-wig', name: 'Wigan', country: 'England', league_id: 'l1' },
  { id: 'l1-wyc', name: 'Wycombe', country: 'England', league_id: 'l1' },

  // --- League 2 (24) ---
  { id: 'l2-acc', name: 'Accrington', country: 'England', league_id: 'l2' },
  { id: 'l2-bar', name: 'Barnet', country: 'England', league_id: 'l2' },
  { id: 'l2-bar2', name: 'Barrow', country: 'England', league_id: 'l2' },
  { id: 'l2-bri', name: 'Bristol Rovers', country: 'England', league_id: 'l2' },
  { id: 'l2-bro', name: 'Bromley', country: 'England', league_id: 'l2' },
  { id: 'l2-cam', name: 'Cambridge Utd', country: 'England', league_id: 'l2' },
  { id: 'l2-che', name: 'Cheltenham', country: 'England', league_id: 'l2' },
  { id: 'l2-che2', name: 'Chesterfield', country: 'England', league_id: 'l2' },
  { id: 'l2-col', name: 'Colchester', country: 'England', league_id: 'l2' },
  { id: 'l2-cra', name: 'Crawley Town', country: 'England', league_id: 'l2' },
  { id: 'l2-cre', name: 'Crewe', country: 'England', league_id: 'l2' },
  { id: 'l2-fle', name: 'Fleetwood', country: 'England', league_id: 'l2' },
  { id: 'l2-gil', name: 'Gillingham', country: 'England', league_id: 'l2' },
  { id: 'l2-gri', name: 'Grimsby', country: 'England', league_id: 'l2' },
  { id: 'l2-har', name: 'Harrogate', country: 'England', league_id: 'l2' },
  { id: 'l2-mkd', name: 'MK Dons', country: 'England', league_id: 'l2' },
  { id: 'l2-new', name: 'Newport County', country: 'Wales', league_id: 'l2' },
  { id: 'l2-not', name: 'Notts County', country: 'England', league_id: 'l2' },
  { id: 'l2-old', name: 'Oldham Athletic', country: 'England', league_id: 'l2' },
  { id: 'l2-sal', name: 'Salford City', country: 'England', league_id: 'l2' },
  { id: 'l2-shr', name: 'Shrewsbury', country: 'England', league_id: 'l2' },
  { id: 'l2-swi', name: 'Swindon', country: 'England', league_id: 'l2' },
  { id: 'l2-tra', name: 'Tranmere', country: 'England', league_id: 'l2' },
  { id: 'l2-wal', name: 'Walsall', country: 'England', league_id: 'l2' },

  // --- Scottish Premiership (12) ---
  { id: 'spl-abe', name: 'Aberdeen', country: 'Scotland', league_id: 'spl' },
  { id: 'spl-cel', name: 'Celtic', country: 'Scotland', league_id: 'spl' },
  { id: 'spl-dun', name: 'Dundee', country: 'Scotland', league_id: 'spl' },
  { id: 'spl-dun2', name: 'Dundee Utd', country: 'Scotland', league_id: 'spl' },
  { id: 'spl-fal', name: 'Falkirk', country: 'Scotland', league_id: 'spl' },
  { id: 'spl-hea', name: 'Hearts', country: 'Scotland', league_id: 'spl' },
  { id: 'spl-hib', name: 'Hibernian', country: 'Scotland', league_id: 'spl' },
  { id: 'spl-kil', name: 'Kilmarnock', country: 'Scotland', league_id: 'spl' },
  { id: 'spl-liv', name: 'Livingston', country: 'Scotland', league_id: 'spl' },
  { id: 'spl-mot', name: 'Motherwell', country: 'Scotland', league_id: 'spl' },
  { id: 'spl-ran', name: 'Rangers', country: 'Scotland', league_id: 'spl' },
  { id: 'spl-stm', name: 'St Mirren', country: 'Scotland', league_id: 'spl' },

  // --- La Liga (20) ---
  { id: 'lal-ala', name: 'Alavés', country: 'Spain', league_id: 'laliga' },
  { id: 'lal-ath', name: 'Athletic Club', country: 'Spain', league_id: 'laliga' },
  { id: 'lal-atl', name: 'Atlético Madrid', country: 'Spain', league_id: 'laliga' },
  { id: 'lal-bar', name: 'Barcelona', country: 'Spain', league_id: 'laliga' },
  { id: 'lal-cel', name: 'Celta Vigo', country: 'Spain', league_id: 'laliga' },
  { id: 'lal-esp', name: 'Espanyol', country: 'Spain', league_id: 'laliga' },
  { id: 'lal-get', name: 'Getafe', country: 'Spain', league_id: 'laliga' },
  { id: 'lal-gir', name: 'Girona', country: 'Spain', league_id: 'laliga' },
  { id: 'lal-las', name: 'Las Palmas', country: 'Spain', league_id: 'laliga' },
  { id: 'lal-leg', name: 'Leganés', country: 'Spain', league_id: 'laliga' },
  { id: 'lal-mal', name: 'Mallorca', country: 'Spain', league_id: 'laliga' },
  { id: 'lal-osa', name: 'Osasuna', country: 'Spain', league_id: 'laliga' },
  { id: 'lal-ray', name: 'Rayo Vallecano', country: 'Spain', league_id: 'laliga' },
  { id: 'lal-bet', name: 'Real Betis', country: 'Spain', league_id: 'laliga' },
  { id: 'lal-mad', name: 'Real Madrid', country: 'Spain', league_id: 'laliga' },
  { id: 'lal-soc', name: 'Real Sociedad', country: 'Spain', league_id: 'laliga' },
  { id: 'lal-val', name: 'Real Valladolid', country: 'Spain', league_id: 'laliga' },
  { id: 'lal-sev', name: 'Sevilla', country: 'Spain', league_id: 'laliga' },
  { id: 'lal-val2', name: 'Valencia', country: 'Spain', league_id: 'laliga' },
  { id: 'lal-vil', name: 'Villarreal', country: 'Spain', league_id: 'laliga' },

  // --- Bundesliga (18) ---
  { id: 'bun-aug', name: 'Augsburg', country: 'Germany', league_id: 'bundesliga' },
  { id: 'bun-lev', name: 'Bayer Leverkusen', country: 'Germany', league_id: 'bundesliga' },
  { id: 'bun-bay', name: 'Bayern Munich', country: 'Germany', league_id: 'bundesliga' },
  { id: 'bun-boc', name: 'Bochum', country: 'Germany', league_id: 'bundesliga' },
  { id: 'bun-dor', name: 'Dortmund', country: 'Germany', league_id: 'bundesliga' },
  { id: 'bun-gla', name: 'M\'gladbach', country: 'Germany', league_id: 'bundesliga' },
  { id: 'bun-fra', name: 'Eintracht Frankfurt', country: 'Germany', league_id: 'bundesliga' },
  { id: 'bun-fre', name: 'Freiburg', country: 'Germany', league_id: 'bundesliga' },
  { id: 'bun-hei', name: 'Heidenheim', country: 'Germany', league_id: 'bundesliga' },
  { id: 'bun-hof', name: 'Hoffenheim', country: 'Germany', league_id: 'bundesliga' },
  { id: 'bun-kie', name: 'Holstein Kiel', country: 'Germany', league_id: 'bundesliga' },
  { id: 'bun-lei', name: 'RB Leipzig', country: 'Germany', league_id: 'bundesliga' },
  { id: 'bun-mai', name: 'Mainz 05', country: 'Germany', league_id: 'bundesliga' },
  { id: 'bun-stp', name: 'St. Pauli', country: 'Germany', league_id: 'bundesliga' },
  { id: 'bun-stu', name: 'Stuttgart', country: 'Germany', league_id: 'bundesliga' },
  { id: 'bun-uni', name: 'Union Berlin', country: 'Germany', league_id: 'bundesliga' },
  { id: 'bun-wer', name: 'Werder Bremen', country: 'Germany', league_id: 'bundesliga' },
  { id: 'bun-wol', name: 'Wolfsburg', country: 'Germany', league_id: 'bundesliga' },

  // --- Serie A (20) ---
  { id: 'ser-ata', name: 'Atalanta', country: 'Italy', league_id: 'seriea' },
  { id: 'ser-bol', name: 'Bologna', country: 'Italy', league_id: 'seriea' },
  { id: 'ser-cag', name: 'Cagliari', country: 'Italy', league_id: 'seriea' },
  { id: 'ser-com', name: 'Como', country: 'Italy', league_id: 'seriea' },
  { id: 'ser-cre', name: 'Cremonese', country: 'Italy', league_id: 'seriea' },
  { id: 'ser-fio', name: 'Fiorentina', country: 'Italy', league_id: 'seriea' },
  { id: 'ser-gen', name: 'Genoa', country: 'Italy', league_id: 'seriea' },
  { id: 'ser-int', name: 'Inter Milan', country: 'Italy', league_id: 'seriea' },
  { id: 'ser-juv', name: 'Juventus', country: 'Italy', league_id: 'seriea' },
  { id: 'ser-laz', name: 'Lazio', country: 'Italy', league_id: 'seriea' },
  { id: 'ser-lec', name: 'Lecce', country: 'Italy', league_id: 'seriea' },
  { id: 'ser-mil', name: 'AC Milan', country: 'Italy', league_id: 'seriea' },
  { id: 'ser-nap', name: 'Napoli', country: 'Italy', league_id: 'seriea' },
  { id: 'ser-par', name: 'Parma', country: 'Italy', league_id: 'seriea' },
  { id: 'ser-pis', name: 'Pisa', country: 'Italy', league_id: 'seriea' },
  { id: 'ser-rom', name: 'Roma', country: 'Italy', league_id: 'seriea' },
  { id: 'ser-sas', name: 'Sassuolo', country: 'Italy', league_id: 'seriea' },
  { id: 'ser-tor', name: 'Torino', country: 'Italy', league_id: 'seriea' },
  { id: 'ser-udi', name: 'Udinese', country: 'Italy', league_id: 'seriea' },
  { id: 'ser-ver', name: 'Verona', country: 'Italy', league_id: 'seriea' },

  // --- Ligue 1 (18) ---
  { id: 'lig-ang', name: 'Angers', country: 'France', league_id: 'ligue1' },
  { id: 'lig-aux', name: 'Auxerre', country: 'France', league_id: 'ligue1' },
  { id: 'lig-bre', name: 'Brest', country: 'France', league_id: 'ligue1' },
  { id: 'lig-hav', name: 'Le Havre', country: 'France', league_id: 'ligue1' },
  { id: 'lig-len', name: 'Lens', country: 'France', league_id: 'ligue1' },
  { id: 'lig-lil', name: 'Lille', country: 'France', league_id: 'ligue1' },
  { id: 'lig-lor', name: 'Lorient', country: 'France', league_id: 'ligue1' },
  { id: 'lig-lyo', name: 'Lyon', country: 'France', league_id: 'ligue1' },
  { id: 'lig-mar', name: 'Marseille', country: 'France', league_id: 'ligue1' },
  { id: 'lig-met', name: 'Metz', country: 'France', league_id: 'ligue1' },
  { id: 'lig-mon', name: 'Monaco', country: 'France', league_id: 'ligue1' },
  { id: 'lig-nan', name: 'Nantes', country: 'France', league_id: 'ligue1' },
  { id: 'lig-nic', name: 'Nice', country: 'France', league_id: 'ligue1' },
  { id: 'lig-pfc', name: 'Paris FC', country: 'France', league_id: 'ligue1' },
  { id: 'lig-psg', name: 'PSG', country: 'France', league_id: 'ligue1' },
  { id: 'lig-ren', name: 'Rennes', country: 'France', league_id: 'ligue1' },
  { id: 'lig-str', name: 'Strasbourg', country: 'France', league_id: 'ligue1' },
  { id: 'lig-tou', name: 'Toulouse', country: 'France', league_id: 'ligue1' },

  // ==========================
  // COVER LEAGUES
  // ==========================

  // --- Süper Lig (Turkey) (18) ---
  { id: 'tur-ala', name: 'Alanyaspor', country: 'Turkey', league_id: 'superlig' },
  { id: 'tur-ant', name: 'Antalyaspor', country: 'Turkey', league_id: 'superlig' },
  { id: 'tur-bes', name: 'Besiktas', country: 'Turkey', league_id: 'superlig' },
  { id: 'tur-riz', name: 'Caykur Rizespor', country: 'Turkey', league_id: 'superlig' },
  { id: 'tur-eyu', name: 'Eyüpspor', country: 'Turkey', league_id: 'superlig' },
  { id: 'tur-fat', name: 'Fatih Karagümrük', country: 'Turkey', league_id: 'superlig' },
  { id: 'tur-fen', name: 'Fenerbahce', country: 'Turkey', league_id: 'superlig' },
  { id: 'tur-gal', name: 'Galatasaray', country: 'Turkey', league_id: 'superlig' },
  { id: 'tur-gaz', name: 'Gaziantep', country: 'Turkey', league_id: 'superlig' },
  { id: 'tur-gen', name: 'Gençlerbirliği', country: 'Turkey', league_id: 'superlig' },
  { id: 'tur-goz', name: 'Goztepe', country: 'Turkey', league_id: 'superlig' },
  { id: 'tur-bas', name: 'Istanbul Basaksehir', country: 'Turkey', league_id: 'superlig' },
  { id: 'tur-kas', name: 'Kasimpasa', country: 'Turkey', league_id: 'superlig' },
  { id: 'tur-kay', name: 'Kayserispor', country: 'Turkey', league_id: 'superlig' },
  { id: 'tur-koc', name: 'Kocaelispor', country: 'Turkey', league_id: 'superlig' },
  { id: 'tur-kon', name: 'Konyaspor', country: 'Turkey', league_id: 'superlig' },
  { id: 'tur-sam', name: 'Samsunspor', country: 'Turkey', league_id: 'superlig' },
  { id: 'tur-tra', name: 'Trabzonspor', country: 'Turkey', league_id: 'superlig' },

  // --- Liga Portugal (18) ---
  { id: 'por-alv', name: 'Alverca', country: 'Portugal', league_id: 'portugal' },
  { id: 'por-aro', name: 'Arouca', country: 'Portugal', league_id: 'portugal' },
  { id: 'por-avs', name: 'AVS', country: 'Portugal', league_id: 'portugal' },
  { id: 'por-ben', name: 'Benfica', country: 'Portugal', league_id: 'portugal' },
  { id: 'por-bra', name: 'Braga', country: 'Portugal', league_id: 'portugal' },
  { id: 'por-cas', name: 'Casa Pia', country: 'Portugal', league_id: 'portugal' },
  { id: 'por-est', name: 'Estoril', country: 'Portugal', league_id: 'portugal' },
  { id: 'por-ama', name: 'Estrela da Amadora', country: 'Portugal', league_id: 'portugal' },
  { id: 'por-fam', name: 'Famalicao', country: 'Portugal', league_id: 'portugal' },
  { id: 'por-gil', name: 'Gil Vicente', country: 'Portugal', league_id: 'portugal' },
  { id: 'por-more', name: 'Moreirense', country: 'Portugal', league_id: 'portugal' },
  { id: 'por-nac', name: 'Nacional', country: 'Portugal', league_id: 'portugal' },
  { id: 'por-por', name: 'Porto', country: 'Portugal', league_id: 'portugal' },
  { id: 'por-rio', name: 'Rio Ave', country: 'Portugal', league_id: 'portugal' },
  { id: 'por-san', name: 'Santa Clara', country: 'Portugal', league_id: 'portugal' },
  { id: 'por-spo', name: 'Sporting CP', country: 'Portugal', league_id: 'portugal' },
  { id: 'por-ton', name: 'Tondela', country: 'Portugal', league_id: 'portugal' },
  { id: 'por-vit', name: 'Vitoria SC', country: 'Portugal', league_id: 'portugal' },

  // --- Jupiler Pro League (Belgium) (16) ---
  { id: 'bel-and', name: 'Anderlecht', country: 'Belgium', league_id: 'jupiler' },
  { id: 'bel-ant', name: 'Antwerp', country: 'Belgium', league_id: 'jupiler' },
  { id: 'bel-bee', name: 'Beerschot', country: 'Belgium', league_id: 'jupiler' },
  { id: 'bel-cer', name: 'Cercle Brugge', country: 'Belgium', league_id: 'jupiler' },
  { id: 'bel-cha', name: 'Charleroi', country: 'Belgium', league_id: 'jupiler' },
  { id: 'bel-clu', name: 'Club Brugge', country: 'Belgium', league_id: 'jupiler' },
  { id: 'bel-den', name: 'Dender', country: 'Belgium', league_id: 'jupiler' },
  { id: 'bel-gen', name: 'Genk', country: 'Belgium', league_id: 'jupiler' },
  { id: 'bel-gan', name: 'Gent', country: 'Belgium', league_id: 'jupiler' },
  { id: 'bel-kor', name: 'Kortrijk', country: 'Belgium', league_id: 'jupiler' },
  { id: 'bel-mec', name: 'Mechelen', country: 'Belgium', league_id: 'jupiler' },
  { id: 'bel-ohl', name: 'OH Leuven', country: 'Belgium', league_id: 'jupiler' },
  { id: 'bel-sin', name: 'Sint-Truiden', country: 'Belgium', league_id: 'jupiler' },
  { id: 'bel-sta', name: 'Standard Liege', country: 'Belgium', league_id: 'jupiler' },
  { id: 'bel-uni', name: 'Union SG', country: 'Belgium', league_id: 'jupiler' },
  { id: 'bel-wes', name: 'Westerlo', country: 'Belgium', league_id: 'jupiler' },

  // --- Eredivisie (Netherlands) (18) ---
  { id: 'ned-aja', name: 'Ajax', country: 'Netherlands', league_id: 'eredivisie' },
  { id: 'ned-az', name: 'AZ Alkmaar', country: 'Netherlands', league_id: 'eredivisie' },
  { id: 'ned-exc', name: 'Excelsior', country: 'Netherlands', league_id: 'eredivisie' },
  { id: 'ned-fey', name: 'Feyenoord', country: 'Netherlands', league_id: 'eredivisie' },
  { id: 'ned-for', name: 'Fortuna Sittard', country: 'Netherlands', league_id: 'eredivisie' },
  { id: 'ned-gae', name: 'Go Ahead Eagles', country: 'Netherlands', league_id: 'eredivisie' },
  { id: 'ned-gro', name: 'Groningen', country: 'Netherlands', league_id: 'eredivisie' },
  { id: 'ned-hee', name: 'Heerenveen', country: 'Netherlands', league_id: 'eredivisie' },
  { id: 'ned-her', name: 'Heracles', country: 'Netherlands', league_id: 'eredivisie' },
  { id: 'ned-nac', name: 'NAC Breda', country: 'Netherlands', league_id: 'eredivisie' },
  { id: 'ned-nec', name: 'NEC Nijmegen', country: 'Netherlands', league_id: 'eredivisie' },
  { id: 'ned-pec', name: 'PEC Zwolle', country: 'Netherlands', league_id: 'eredivisie' },
  { id: 'ned-psv', name: 'PSV Eindhoven', country: 'Netherlands', league_id: 'eredivisie' },
  { id: 'ned-spa', name: 'Sparta Rotterdam', country: 'Netherlands', league_id: 'eredivisie' },
  { id: 'ned-tel', name: 'Telstar', country: 'Netherlands', league_id: 'eredivisie' },
  { id: 'ned-twe', name: 'Twente', country: 'Netherlands', league_id: 'eredivisie' },
  { id: 'ned-utr', name: 'Utrecht', country: 'Netherlands', league_id: 'eredivisie' },
  { id: 'ned-vol', name: 'Volendam', country: 'Netherlands', league_id: 'eredivisie' },

  // --- Greek Super League (14) ---
  { id: 'gre-aek', name: 'AEK Athens', country: 'Greece', league_id: 'greek' },
  { id: 'gre-ari', name: 'Aris', country: 'Greece', league_id: 'greek' },
  { id: 'gre-ast', name: 'Asteras Tripolis', country: 'Greece', league_id: 'greek' },
  { id: 'gre-atr', name: 'Atromitos', country: 'Greece', league_id: 'greek' },
  { id: 'gre-kal', name: 'Kallithea', country: 'Greece', league_id: 'greek' },
  { id: 'gre-lam', name: 'Lamia', country: 'Greece', league_id: 'greek' },
  { id: 'gre-lev', name: 'Levadiakos', country: 'Greece', league_id: 'greek' },
  { id: 'gre-ofi', name: 'OFI Crete', country: 'Greece', league_id: 'greek' },
  { id: 'gre-oly', name: 'Olympiacos', country: 'Greece', league_id: 'greek' },
  { id: 'gre-pan', name: 'Panathinaikos', country: 'Greece', league_id: 'greek' },
  { id: 'gre-pne', name: 'Panetolikos', country: 'Greece', league_id: 'greek' },
  { id: 'gre-pao', name: 'PAOK', country: 'Greece', league_id: 'greek' },
  { id: 'gre-pan2', name: 'Panserraikos', country: 'Greece', league_id: 'greek' },
  { id: 'gre-vol', name: 'Volos', country: 'Greece', league_id: 'greek' },

  // --- Swiss Super League (12) ---
  { id: 'swi-bas', name: 'Basel', country: 'Switzerland', league_id: 'swiss' },
  { id: 'swi-gra', name: 'Grasshoppers', country: 'Switzerland', league_id: 'swiss' },
  { id: 'swi-laus', name: 'Lausanne-Sport', country: 'Switzerland', league_id: 'swiss' },
  { id: 'swi-lug', name: 'Lugano', country: 'Switzerland', league_id: 'swiss' },
  { id: 'swi-luz', name: 'Luzern', country: 'Switzerland', league_id: 'swiss' },
  { id: 'swi-ser', name: 'Servette', country: 'Switzerland', league_id: 'swiss' },
  { id: 'swi-sio', name: 'Sion', country: 'Switzerland', league_id: 'swiss' },
  { id: 'swi-stg', name: 'St. Gallen', country: 'Switzerland', league_id: 'swiss' },
  { id: 'swi-win', name: 'Winterthur', country: 'Switzerland', league_id: 'swiss' },
  { id: 'swi-ybo', name: 'Young Boys', country: 'Switzerland', league_id: 'swiss' },
  { id: 'swi-yve', name: 'Yverdon-Sport', country: 'Switzerland', league_id: 'swiss' },
  { id: 'swi-zur', name: 'Zurich', country: 'Switzerland', league_id: 'swiss' },

  // --- Austrian Bundesliga (12) ---
  { id: 'aut-alt', name: 'Altach', country: 'Austria', league_id: 'austrian' },
  { id: 'aut-aus', name: 'Austria Klagenfurt', country: 'Austria', league_id: 'austrian' },
  { id: 'aut-vie', name: 'Austria Vienna', country: 'Austria', league_id: 'austrian' },
  { id: 'aut-bwl', name: 'Blau-Weiß Linz', country: 'Austria', league_id: 'austrian' },
  { id: 'aut-gak', name: 'Grazer AK', country: 'Austria', league_id: 'austrian' },
  { id: 'aut-har', name: 'Hartberg', country: 'Austria', league_id: 'austrian' },
  { id: 'aut-las', name: 'LASK', country: 'Austria', league_id: 'austrian' },
  { id: 'aut-rap', name: 'Rapid Vienna', country: 'Austria', league_id: 'austrian' },
  { id: 'aut-sal', name: 'Red Bull Salzburg', country: 'Austria', league_id: 'austrian' },
  { id: 'aut-stu', name: 'Sturm Graz', country: 'Austria', league_id: 'austrian' },
  { id: 'aut-tir', name: 'WSG Tirol', country: 'Austria', league_id: 'austrian' },
  { id: 'aut-wol', name: 'Wolfsberger', country: 'Austria', league_id: 'austrian' },

  // --- Danish Superliga (12) ---
  { id: 'den-aab', name: 'AaB', country: 'Denmark', league_id: 'danish' },
  { id: 'den-arh', name: 'AGF', country: 'Denmark', league_id: 'danish' },
  { id: 'den-bro', name: 'Brondby', country: 'Denmark', league_id: 'danish' },
  { id: 'den-cop', name: 'FC Copenhagen', country: 'Denmark', league_id: 'danish' },
  { id: 'den-mid', name: 'Midtjylland', country: 'Denmark', league_id: 'danish' },
  { id: 'den-nor', name: 'Nordsjaelland', country: 'Denmark', league_id: 'danish' },
  { id: 'den-lyn', name: 'Lyngby', country: 'Denmark', league_id: 'danish' },
  { id: 'den-ran', name: 'Randers', country: 'Denmark', league_id: 'danish' },
  { id: 'den-sil', name: 'Silkeborg', country: 'Denmark', league_id: 'danish' },
  { id: 'den-son', name: 'Sonderjyske', country: 'Denmark', league_id: 'danish' },
  { id: 'den-vej', name: 'Vejle', country: 'Denmark', league_id: 'danish' },
  { id: 'den-vib', name: 'Viborg', country: 'Denmark', league_id: 'danish' },

  // --- Norwegian Eliteserien (16) ---
  { id: 'nor-bod', name: 'Bodo/Glimt', country: 'Norway', league_id: 'norwegian' },
  { id: 'nor-bra', name: 'Brann', country: 'Norway', league_id: 'norwegian' },
  { id: 'nor-fre', name: 'Fredrikstad', country: 'Norway', league_id: 'norwegian' },
  { id: 'nor-ham', name: 'HamKam', country: 'Norway', league_id: 'norwegian' },
  { id: 'nor-hau', name: 'Haugesund', country: 'Norway', league_id: 'norwegian' },
  { id: 'nor-kfu', name: 'KFUM Oslo', country: 'Norway', league_id: 'norwegian' },
  { id: 'nor-kri', name: 'Kristiansund', country: 'Norway', league_id: 'norwegian' },
  { id: 'nor-lil', name: 'Lillestrom', country: 'Norway', league_id: 'norwegian' },
  { id: 'nor-mol', name: 'Molde', country: 'Norway', league_id: 'norwegian' },
  { id: 'nor-odd', name: 'Odd', country: 'Norway', league_id: 'norwegian' },
  { id: 'nor-ros', name: 'Rosenborg', country: 'Norway', league_id: 'norwegian' },
  { id: 'nor-san', name: 'Sandefjord', country: 'Norway', league_id: 'norwegian' },
  { id: 'nor-srp', name: 'Sarpsborg 08', country: 'Norway', league_id: 'norwegian' },
  { id: 'nor-str', name: 'Stromsgodset', country: 'Norway', league_id: 'norwegian' },
  { id: 'nor-tro', name: 'Tromso', country: 'Norway', league_id: 'norwegian' },
  { id: 'nor-vik', name: 'Viking', country: 'Norway', league_id: 'norwegian' },

  // --- Swedish Allsvenskan (16) ---
  { id: 'swe-aik', name: 'AIK', country: 'Sweden', league_id: 'swedish' },
  { id: 'swe-bro', name: 'Brommapojkarna', country: 'Sweden', league_id: 'swedish' },
  { id: 'swe-dju', name: 'Djurgarden', country: 'Sweden', league_id: 'swedish' },
  { id: 'swe-gai', name: 'GAIS', country: 'Sweden', league_id: 'swedish' },
  { id: 'swe-hal', name: 'Halmstad', country: 'Sweden', league_id: 'swedish' },
  { id: 'swe-ham', name: 'Hammarby', country: 'Sweden', league_id: 'swedish' },
  { id: 'swe-hac', name: 'Hacken', country: 'Sweden', league_id: 'swedish' },
  { id: 'swe-elf', name: 'Elfsborg', country: 'Sweden', league_id: 'swedish' },
  { id: 'swe-got', name: 'IFK Goteborg', country: 'Sweden', league_id: 'swedish' },
  { id: 'swe-nor', name: 'IFK Norrkoping', country: 'Sweden', league_id: 'swedish' },
  { id: 'swe-var', name: 'IFK Varnamo', country: 'Sweden', league_id: 'swedish' },
  { id: 'swe-kal', name: 'Kalmar', country: 'Sweden', league_id: 'swedish' },
  { id: 'swe-mal', name: 'Malmo FF', country: 'Sweden', league_id: 'swedish' },
  { id: 'swe-mja', name: 'Mjallby', country: 'Sweden', league_id: 'swedish' },
  { id: 'swe-sir', name: 'Sirius', country: 'Sweden', league_id: 'swedish' },
  { id: 'swe-vas', name: 'Vasteras SK', country: 'Sweden', league_id: 'swedish' },

  // --- Czech First League (16) ---
  { id: 'cze-ban', name: 'Banik Ostrava', country: 'Czech Republic', league_id: 'czech' },
  { id: 'cze-boh', name: 'Bohemians 1905', country: 'Czech Republic', league_id: 'czech' },
  { id: 'cze-bude', name: 'Ceske Budejovice', country: 'Czech Republic', league_id: 'czech' },
  { id: 'cze-duk', name: 'Dukla Prague', country: 'Czech Republic', league_id: 'czech' },
  { id: 'cze-hra', name: 'Hradec Kralove', country: 'Czech Republic', league_id: 'czech' },
  { id: 'cze-jab', name: 'Jablonec', country: 'Czech Republic', league_id: 'czech' },
  { id: 'cze-kar', name: 'Karvina', country: 'Czech Republic', league_id: 'czech' },
  { id: 'cze-lib', name: 'Slovan Liberec', country: 'Czech Republic', league_id: 'czech' },
  { id: 'cze-mla', name: 'Mlada Boleslav', country: 'Czech Republic', league_id: 'czech' },
  { id: 'cze-olo', name: 'Sigma Olomouc', country: 'Czech Republic', league_id: 'czech' },
  { id: 'cze-par', name: 'Pardubice', country: 'Czech Republic', league_id: 'czech' },
  { id: 'cze-plz', name: 'Viktoria Plzen', country: 'Czech Republic', league_id: 'czech' },
  { id: 'cze-sla', name: 'Slavia Prague', country: 'Czech Republic', league_id: 'czech' },
  { id: 'cze-spa', name: 'Sparta Prague', country: 'Czech Republic', league_id: 'czech' },
  { id: 'cze-slo', name: 'Slovacko', country: 'Czech Republic', league_id: 'czech' },
  { id: 'cze-tep', name: 'Teplice', country: 'Czech Republic', league_id: 'czech' },

  // --- Croatian Football League (10) ---
  { id: 'cro-din', name: 'Dinamo Zagreb', country: 'Croatia', league_id: 'croatian' },
  { id: 'cro-gor', name: 'Gorica', country: 'Croatia', league_id: 'croatian' },
  { id: 'cro-haj', name: 'Hajduk Split', country: 'Croatia', league_id: 'croatian' },
  { id: 'cro-ist', name: 'Istra 1961', country: 'Croatia', league_id: 'croatian' },
  { id: 'cro-lok', name: 'Lokomotiva', country: 'Croatia', league_id: 'croatian' },
  { id: 'cro-osi', name: 'Osijek', country: 'Croatia', league_id: 'croatian' },
  { id: 'cro-rij', name: 'Rijeka', country: 'Croatia', league_id: 'croatian' },
  { id: 'cro-sla', name: 'Slaven Belupo', country: 'Croatia', league_id: 'croatian' },
  { id: 'cro-sib', name: 'Sibenik', country: 'Croatia', league_id: 'croatian' },
  { id: 'cro-var', name: 'Varazdin', country: 'Croatia', league_id: 'croatian' },

  // --- Polish Ekstraklasa (18) ---
  { id: 'pol-cra', name: 'Cracovia', country: 'Poland', league_id: 'polish' },
  { id: 'pol-gks', name: 'GKS Katowice', country: 'Poland', league_id: 'polish' },
  { id: 'pol-gor', name: 'Gornik Zabrze', country: 'Poland', league_id: 'polish' },
  { id: 'pol-jag', name: 'Jagiellonia', country: 'Poland', league_id: 'polish' },
  { id: 'pol-kor', name: 'Korona Kielce', country: 'Poland', league_id: 'polish' },
  { id: 'pol-lec', name: 'Lech Poznan', country: 'Poland', league_id: 'polish' },
  { id: 'pol-leg', name: 'Legia Warsaw', country: 'Poland', league_id: 'polish' },
  { id: 'pol-lec2', name: 'Lechia Gdansk', country: 'Poland', league_id: 'polish' },
  { id: 'pol-mot', name: 'Motor Lublin', country: 'Poland', league_id: 'polish' },
  { id: 'pol-pia', name: 'Piast Gliwice', country: 'Poland', league_id: 'polish' },
  { id: 'pol-pog', name: 'Pogon Szczecin', country: 'Poland', league_id: 'polish' },
  { id: 'pol-pus', name: 'Puszcza Niepolomice', country: 'Poland', league_id: 'polish' },
  { id: 'pol-rad', name: 'Radomiak Radom', country: 'Poland', league_id: 'polish' },
  { id: 'pol-rak', name: 'Rakow Czestochowa', country: 'Poland', league_id: 'polish' },
  { id: 'pol-sta', name: 'Stal Mielec', country: 'Poland', league_id: 'polish' },
  { id: 'pol-wid', name: 'Widzew Lodz', country: 'Poland', league_id: 'polish' },
  { id: 'pol-zag', name: 'Zaglebie Lubin', country: 'Poland', league_id: 'polish' },
  { id: 'pol-sla', name: 'Slask Wroclaw', country: 'Poland', league_id: 'polish' },
];